### ISSUE TITLE
Установка конфигурации Тестирование 3.0

### ISSUE THREAD

**Issue by IvanFromUa** [ivanov660/TestingTool-3#118]
Доброго времени суток!
Как поместить в конфигуратор конфигурацию Тестирование 3.0?

При попытке загрузить конфигурацию из файлов ("Конфигурация->"Загрузить конфигурацию из файлов", конфигуратор 1С, ругается:
"Возможно содержимое каталога: "...\TestingTool-3-master\src" не является корректной xml выгрузкой"

**Comment by ivanov660** [comment]
У вас есть два варианта:
1. Использовать конфигурацию из папки [релизы ](https://github.com/ivanov660/TestingTool-3/releases). В ней скомпилированная последняя версия
2. Использовать EDT для загрузки файлов и компиляции проекта.

Проект предназначен для разработке в EDT, файлы проекта не совместимы с конфигуратором (так сделали 1Сники)
