### ISSUE TITLE
Закрытие всех форм внутри тестируемого приложения

### ISSUE THREAD

**Issue by uramalyutin** [ivanov660/TestingTool-3#33]
Не хватает команды закрытия всех форм внутри тестируемого клиента. Если можно, сделайте одной из доступных команд редактора сценариев. 
Пока вышел из положения добавлением команды "Код клиента" с кодом:

`Пока Истина Цикл
	// 1. Попробуем найти диалоги с пользователем и нажать в них "Нет"
	Диалоги = ТестовоеПриложение.НайтиОбъекты(Тип("ТестируемоеОкноКлиентскогоПриложения"), "1?:*"); // 1С:Предприятие или 1S:Enterprise
	Для Каждого лДиалог из Диалоги Цикл
		лКнопка = лДиалог.НайтиОбъект(Тип("ТестируемаяКнопкаФормы"), "Нет");
		Если лКнопка = Неопределено Тогда
			лКнопка = лДиалог.НайтиОбъект(Тип("ТестируемаяКнопкаФормы"), "No"); // Ну а вдруг... :)
		КонецЕсли;
		Если лКнопка = Неопределено Тогда
			Продолжить;	
		КонецЕсли;
		лКнопка.Нажать();		
	КонецЦикла;
	///1
	
	// 2. Попробуем получить все открытые формы и закрыть их	
	Окна = ТестовоеПриложение.ПолучитьПодчиненныеОбъекты();
	Для Каждого лОкно Из Окна Цикл
		Если Не лОкно.Основное Тогда
			Попытка
				лОкно.Закрыть();
			Исключение
			КонецПопытки;
			// 3. Если форма не закрылась, возможно активно какое-то поле формы. Попробуем сделать отмену редактирования для этого поля.
			Попытка
				лПолеВвода = лОкно.ПолучитьОбъект().ПолучитьТекущийЭлемент();
			Исключение
				Продолжить;
			КонецПопытки;
			Если ТипЗнч(лПолеВвода) = Тип("ТестируемоеПолеФормы") Тогда
				Если лПолеВвода.Вид = ВидПоляФормы.ПолеВвода Тогда
					Попытка
						лПолеВвода.ОтменитьРедактирование();
					Исключение
					КонецПопытки;
				КонецЕсли;
			КонецЕсли;
			///3		    		    	
		КонецЕсли;
	КонецЦикла;
	///2
	
	// 4. Если все окна закрыты, нужно прервать цикл.
	прОкна = ТестовоеПриложение.ПолучитьПодчиненныеОбъекты();
	Если прОкна.Количество() = 1 Тогда // Должно остаться только основное окно программы
		Прервать;
	КонецЕсли;
	///4	    	
КонецЦикла;`

**Comment by ivanov660** [comment]
Добрый день!

1) Мы решали данный вопрос сначала через произвольный код клиент. Потом использовали подключение через "Библиотеку шагов".
2) Далее мы сменили логику построения и выполнения сценариев. Что позволило в итоге не сталкиваться с данной проблемой. И данный код нами более не используется. 
Для игрового моделирования такой вариант будет востребован.
3) Мы думали над "пользовательскими/кастомными" командами, однако пока не совсем понятно их отличие от "Библиотеки шагов" (если с шага снять свойство "это блок готовых шагов", будет обычный скрипт) - если только вставка без ограничений на изменение.
4) **Расскажите о проблемах с которыми вы столкнулись**, что заставляет использовать подобные ухищрения. Думаю, что возможно иное решение проблемы.

**Comment by uramalyutin** [comment]
Спасибо за отклик.
Возможно моё пожелание возникло от недопонимания логики выполнения сценариев, благодаря которой вы не сталкиваетесь с проблемой. Тогда дайте, пожалуйста, ссылку на документацию (если есть), где можно об этом прочитать.
Я же сейчас готовлю презентацию для руководства и для этого потихоньку "переношу" сценарии, которые у нас реализованы с помощью другого проекта (https://github.com/grumagargler/tester, приведенный мной код как раз оттуда, и там он очень востребован).
Этот код, по моему представлению, должен вызываться перед выполнением каждого сценария, на случай если после выполнения предыдущего сценария в тестируемом клиенте остались незакрытые формы. Этот код безусловно закрывает все формы и оставляет только основное окно (если предыдущий сценарий не выполнился из-за ошибки и остались открытые окна или, например, осталась форма "Заказ клиента (создание)", то создание нового заказа всегда будет открывать эту форму, и т.д.).
Повторюсь, я пока еще только пишу сценарии, которые у нас уже есть, сам процесс запуска и выполнения сценариев по расписанию испытывал только на одном из них, возможно поэтому у меня и возникло недопонимание как запускаются и выполняются сценарии (больше одного). Если это так, прошу меня извинить, за, возможно, глупые вопросы.

**Comment by ivanov660** [comment]
Рекомендации от нас по опыту использования уже в течении 3-х лет на данный момент. Читайте **по жирному** если не понятно, то детализация.
(Могу с вами пообщаться по скайпу, для того чтобы прояснить некоторые стороны и проблемы, для меня будет ценна обратная связь. Вопросы не глупые, подход разный.)

1. **Сценарные тесты необходимо создавать из наборов блоков (библиотека)**. Это позволит их затем актуализировать с минимальными изменениями. Не создавайте сценарный тест из одной цепочки целиком.
Про эту идею смотрите в [видео уроках](https://github.com/ivanov660/TestingTool-3/wiki/Видео-уроки), к примеру, Урок 1. Создание сценарного UI теста "Процесс продажи товаров" для платформы 1С ERP/УТ 11.

2. **Делайте сценарные тесты параметризированными**. Между блоками передавайте параметры, к примеру, номер заказа как распоряжение. Статью на тему как создавать сценарные тесты, я планирую опубликовать в ближайшее время. Как передаются сморите в видео-уроках.

3. **Каждый сценарный тест должен выполнять проверку одного бизнес процесса**. Хорошо описывает принцип единственности ответственности. Это повышает прозрачность/понятность выполнения тестов и анализа результатов - особенно **для бизнеса**. 

4. **Называйте сценарии понятно** к примеру, по процессу: БП продажа товара с оплатой по эквайрингу.  Это повышает прозрачность/понятность выполнения тестов и анализа результатов - особенно **для бизнеса**. 

![image](https://user-images.githubusercontent.com/24763549/49291677-2f561600-f4bc-11e8-9cbd-c6a301403d73.png)

5. **Каждый тест должен быть независимым от других**. К примеру, если вы сделаете тест продажи, зависящим от поступления, то при падении теста поступления, у вас автоматически упадет тест продажи.

6. **Запускайте каждый сценарный тест в отдельном задании**. Не стоит в одном сценарном тесте запускать кучу разнородных сценариев и действий. Это позволит снизить неожидаемое паразитное влияние, повысит стабильность выполнения, повысит ценность результатов. [как создавать задания](https://infostart.ru/public/856724/)

7. **Распараллеливайте запуск сценарных тестов**. У нас суммарное время выполнения сценариев более 5 часов, при разбиении параллельно мы сократили время выполнения до 30 минут (несколько параллельных волн).

8. **Не пытайтесь покрыть необъятное**. Ни в коем случае не надо ставить целью любыми способами покрыть все возможные комбинации и нажатия кнопок и т.п. Это бессмысленно и экономически дорого. Найти все 100% ошибок очень дорого и практически не достижимо.

![image](https://user-images.githubusercontent.com/24763549/49292308-f7e86900-f4bd-11e8-99aa-df37fe5ed0cc.png)

9. **Не усложняйте, если не требуется**. Разбейте/декомпозируйте один большой проверяющий все тест на несколько маленьких. Чем проще тем понятнее, проще ловить ошибки, проще создавать и т.д.

10. **Включайте сохранение скриншотов ошибок**. При выполнении тестов включайте сохранение снимков экранов. Это позволит быстрее понять причину ошибки и разобраться в ситуации.

11. **Создавайте свои сценарии переносимыми**. Сценарии должны быть легко переносимыми между окружением. Не привязывайте сценарий к одной конкретной базе или машине (только этот справочник по коду 07 или пользователь Иванов и т.п.). Это позволит вам потом легко управлять автоматизацией тестирования.

12. **Все тесты должны быть зелеными**. По результатам нельзя в цепочке оставлять тесты с желтым и красным - их либо исправляете или удаляете из цикла тестирования.

13. **Управляйте проверками (asser/verify) в тесте**. Иногда нужно проверить на значение, и прервать тест, т.к. дальнейшее выполнение будет бессмысленным (assert, сравнить с данными). В некоторых случаях требуется выполнить ряд проверок без падения (varify, сравнить с данными и пропустить при ошибке), т.к. могут упасть сразу несколько сравнений и для отладки каждого вам может понадобиться большое количество запусков.

14. **Обязательно делайте отчеты**. Отчеты помогут вам понять и сохранить во времени результаты тестирования.

15. **Всегда используйте принципы разработки и паттерны тестов**. Это логично)

**Comment by ivanov660** [comment]
надо будет запилить по этой теме статью на инфостарте))) вроде получилось хорошо, заодно и узнаем много хорошего или других мнений от коллег.

**Comment by ivanov660** [comment]
@uramalyutin чем-то еще можем помочь или закроем issue?

**Comment by uramalyutin** [comment]
Закрывайте, конечно, на свой вопрос я получил исчерпывающий ответ :) 
Других вопросов пока нет.
