### ISSUE TITLE
Добавить поддержку DDT

### ISSUE THREAD

**Issue by TestingTool-3** [ivanov660/TestingTool-3#35]
*цель* добавить поддержку Data driven testing
*Задача*
1. Для запуска необходимо использовать файл с данными для загрузки в параметры 
2. Поддерживать полный перебор параметров

**Comment by ivanov660** [comment]
**задача выполнена**

Добавлена в менеджер опция для установки использования DDT на вкладке параметры. После ее установки появляется возможность выбрать файл с макетом формата mxl.
Добавлена поддержка в командную строку запуска
Добавлены в конструктор и конфигурацию поддержка для теста пути файла.
