### ISSUE TITLE
Ошибка при получении представления ячейки табличного поля

### ISSUE THREAD

**Issue by SolovevaIV** [ivanov660/TestingTool-3#37]
**Возникает ошибка при попытке получить значение ячейки таблицы**
Четкое и краткое описание ошибки или не верного поведения.

**Воспроизведение**
Шаги по воспроизведению ошибки:
1. Загружаю обработку Менеджер сценарного теста
2. Пишу тест
3. Создаю параметр
4. Пытаюсь получить представление ячейки таблицы командами:
        -Получить представление данных
        -Команда : ПолучитьПредставлениеДанных
        -Сравнить данные

**Ожидаемое поведение**
Значение ячейки записывается в указанный параметр

**Screenshots**
![default](https://user-images.githubusercontent.com/46512357/51906772-55296980-23de-11e9-84c3-987dedd52c26.png)

**Desktop (please complete the following information):**
 - OS: Win 8.1
 - Version 2018.12.08

**Дополнительно**
Есть ли способ как то получить значение ячейки таблицы

**Comment by ivanov660** [comment]
Добрый день!

**Проблема на сколько я понял следующая**:
Вы пытаетесь получить представление данных табличной части.

**Причины**
Непонятное ограничение от API от 1С. В документации сказано:
Если метод вызывается для поля, являющегося колонкой таблицы, которая не находится в режиме редактирования, будет сгенерирована ошибка.


**Решаемая задача** Напишите подробнее решаемую задачу, думаю что сможем дать более верный совет по созданию теста.

**Обходные пути**
1. Изменить алгоритм теста. Чтобы дать совет нам нужно понять что Вы хотите сделать.
2.! **Думаю что поможет** Сделать фейковое изменение формы см. ниже. 
 а) Открыть через еще изменить форму
 б) Взять и перенести "Клиента" из списка формы на любую группу
 в) Теперь можно получить значение представления
3. Воспользоваться сторонним API (Microsoft Automation UI) для получения значения, тут тоже не так все просто. Можно делать микс в сценарии применения разных апи.
4. Воспользоваться API Selenium  (браузер), есть также свои сложности - в частности нет команд перехода к строке, окон и т.д. - оперируем divами и др.

![image](https://user-images.githubusercontent.com/24763549/51971028-51065600-2489-11e9-89fd-93bad60324bf.png)

**Comment by SolovevaIV** [comment]
Добрый день!

![image](https://user-images.githubusercontent.com/46512357/51980307-1e6c5580-24a9-11e9-8191-376da7cf06fe.png)

Необходимо получить значение выбранной ячейки.
Ваш способ, к сожалению, применить не получилось, так как при каждом запуске приложения настройки не сохраняются.
Пробовали создать сценарий, по которому будем изменять поле таблицы на поле формы, к сожалению, в Менеджере сценарного тестирования нет команды перемещения (Drap&Drop), и сами элементы дерева он распознать не может.

Может быть есть методы, с помощью которых можно получить данное значение

**Comment by ivanov660** [comment]
**Замечания**
1. Настройки обычно сохраняются, если конечно не специфичный случай
2. 1С API не предоставляет подобных вольностей - Drag&Drop работу с мышкой и клавиатурой. 

**Предложения**
1. Попробуйте следующий вариант.
 а) позиционируетесь на строке, затем на поле
 б) далее через еще открываете форму расширенного или обычного поиска
 в) в форме становитесь на поле ввода "что искать" и получаете представление. см. рис ниже.

2. Иногда можно модифицировать формы конфигурации, воспользоваться расширением или создать дополнительную обработку - с необходимым функционалом для теста


![image](https://user-images.githubusercontent.com/24763549/52075663-e6930a00-259d-11e9-8832-9fc5240864cd.png)
![image](https://user-images.githubusercontent.com/24763549/52075674-ec88eb00-259d-11e9-853a-6b4cf4a7fe91.png)

**Comment by SolovevaIV** [comment]
Спасибо большое за варианты, будем применять. Ждем видеоуроков :)

**Comment by ivanov660** [comment]
@SolovevaIV могли бы вы детализировать по видео-урокам. Заранее спасибо.
1) А в каком направлении и о чем интересно было бы чтобы мы рассказали в видео уроках? Примеры использования, первые шаги, что-то другое? 
2) Какие темы не раскрыты?
3) Какие возникают сложности при использовании инструментов?

**Comment by SolovevaIV** [comment]
Возникают некоторые вопросы, скорее связанные с моим недопониманием, в частности:
1. Я создаю тесты с помощью менеджера сценарного теста
2. Я хочу запускать их по нажатию пары кнопок
3. Для этого мне необходимо добавить их в планировщик
4. С помощью конструктора я добавляю тесты в задания
5. Далее возникают трудности, а именно в чем заключается отличие проверки от прохождения самого теста

В моем понимании мне необходимо созданные тесты добавить в какой-либо локальный репозиторий, и выбранные мною тесты запускать, по результатам окончания процесса выполнения тестов я формирую отчет.

Не могу разобраться когда какие элементы конфигурации применять, так как для меня остался не раскрыт полный процесс тестирования.

А видео-уроки буду ждать по применению WinAutomationUI, надеюсь они будут:)

**Comment by ivanov660** [comment]
1. Да, все верно. Менеджер сценарного теста это полноценный IDE. В нем создаются тесты с использованием записи и/или в режиме конструктора.

2. Чтобы тесты запускались по нажатию "пары кнопок" необходимо использовать конфигурацию "тестирование". Для этого последовательно необходимо сделать следующую последовательность действий (настройку базы не рассматриваем) Пример видео: [запуск и выполнение тестов](https://www.youtube.com/watch?v=EUZ8OEyaHP0&feature=youtu.be)
     а) Подсистема тестирование. Создать новый элемент в справочнике "Тесты", указав путь к сценарию тестирования.
     б) Подсистема планировщик. Создать новое задание с помощью конструктора заданий "Сценарий UI" и указать элемент справочника а) в качестве теста.
     в) Подсистема планировщик. Создать новое задание проверки (одно на тестируемую базу) или в текущее задание проверки добавить задание выполнения теста шаг б)

3. Чтобы проверка запускалась автоматически, то ее можно добавить в планировщик и настроить расписание.

4. Совершенно верно. Пункт выше 2 б).

5. Поясняю. 
Обычное задание - запускает 1 (один) тест.
Задание проверки - запускает "все" тесты (там в конструкторе есть табличка, где указываете список обычных заданий). Это последовательный и параллельный запуск всех тестов (ожидание прохождения всех тестов). И все выполненные тесты в рамках проверки получают один идентификатор в отчете. 

Поясню на пальцах)
* Вот вы запустили один тест вручную, потом второй и т.д., и сохраняете отчет (xml) в корень диска. * Как понять что они были выполнены для сегодняшней проверки, как их выделить из общего числа файлов? 
* Для порядка вы создаете в корне каталог - называете его "№50" или "дата 05.02.2019". И все файлы отчетов сохраняете в этот каталог. 
* Теперь, вы можете понять, что каталог с "дата 05.02.2019" хранятся все результаты за сегодня.
* Задание проверки выполняет такую же операцию в базе данных.

![image](https://user-images.githubusercontent.com/24763549/52276306-e8c0e400-2962-11e9-8eb6-1456cfd46a2c.png)

> В моем понимании мне необходимо созданные тесты добавить в какой-либо локальный репозиторий, и выбранные мною тесты запускать, по результатам окончания процесса выполнения тестов я формирую отчет.

А) Да, Вы добавляете все файлы тестов в репозиторий - оптимально GIT.
Б) Если вы запускаете тесты вручную, а не автоматически. Загружайте их с помощью обработки (загрузка отчетов allure или Juint - зависит от выбранного формата). 
При загрузке указываете номер проверки (создаете новую, если проверяете новый релиз) и  базу на которой выполняете тестирование.
В) Отчет  - это обработка AllureSkin автоматически формирует отчет, как только вы подгружаете новые результаты

> Не могу разобраться когда какие элементы конфигурации применять, так как для меня остался не раскрыт полный процесс тестирования.

Подсистемы: 
 Тестирование  - все что связано с тестами 
 Планировщик - все что связано с заданиями
Справочники:
 Тесты - указываете имя теста и путь к файлам сценария
 Задание - позволяет запускать автоматически один тест или проверку (все тесты)
 Тестируемый клиент и база 1с - указываете параметры базы, на которой проверяете.
 Дополнительные обработки - полезные отчеты и действия
 Проверка - сущность по которой можно сгруппировать результаты тестов

**Comment by SolovevaIV** [comment]
Огромное спасибо за помощь. Теперь все стало намного яснее!

**Comment by SolovevaIV** [comment]
Добрый день!
Не удается запустить тесты, не знаю в чем может быть проблема:
1. Создала сценарные тесты (загрузила из файла скрипт, который создан с помощью менеджера сценарного теста)
![image](https://user-images.githubusercontent.com/46512357/52459043-5005b080-2b7c-11e9-8069-8abe90320af3.png)

2. Перехожу в планировщик для создания задания.
3. По кнопке "Создать по шаблону" почему то нет шаблонов, поэтому загружаю конструктор из файла
![image](https://user-images.githubusercontent.com/46512357/52459090-965b0f80-2b7c-11e9-99ec-ea3f5c8b2a47.png)
4. Создала задание и задание проверку
![image](https://user-images.githubusercontent.com/46512357/52459118-af63c080-2b7c-11e9-9488-4239e9b34954.png)
5. Перехожу в планировщик и создаю задание для выполнения
![image](https://user-images.githubusercontent.com/46512357/52459145-dde19b80-2b7c-11e9-969f-8ddc84c06269.png)
6. Для выполнения задания нажимаю "Выполнить сейчас" и перехожу в "Обзор и управление выполнением заданий"
![image](https://user-images.githubusercontent.com/46512357/52459197-27ca8180-2b7d-11e9-8e35-14daa0c0fe1b.png)

Тесты не выполняются, указаны по два раза потому что один набор тестов для текущей 22 сборки и такой же набор для 12 сборки (прекратить ее не получается)

Насколько я понимаю может быть проблема в настройке базы. Хотелось бы узнать, что необходимо указывать в настройке Тестируемые клиенты? Как я поняла, большинство значений переменных берется из этой настройки.
![image](https://user-images.githubusercontent.com/46512357/52459728-539b3680-2b80-11e9-97f6-82a33c33456f.png)
Сами настройки базы указаны верно

**Comment by ivanov660** [comment]
по порядку:
1. Для того чтобы заработал п.3. Вам надо выполнить следующие действия:
  а) перейти в подсистему "Администрирование"
  б) открыть "Дополнительные отчеты и обработки"
  в) загрузить обработки из файлов: 
![image](https://user-images.githubusercontent.com/24763549/52477663-ca055c00-2bb3-11e9-8698-2106897e2685.png)
 г) открыть "настройка создания заданий" и указать в списке, те обработки, которые являются заданиями:
![image](https://user-images.githubusercontent.com/24763549/52477711-f6b97380-2bb3-11e9-9dbd-99da63194da5.png)

2) Чтобы для пользователя открывалась всегда обработка allure skin на рабочем столе, необходимо
 а) загрузить обработку AllreSkin дополнительные отчеты и обработки
 в) далее открыть "настройки рабочего места начальной страницы "
 г) создать запись, указать пользователя и обработку
![image](https://user-images.githubusercontent.com/24763549/52477815-557eed00-2bb4-11e9-847a-0185ea98db74.png)

3) Давайте проверим что настроено регламентное задание (судя по всему - оно не настроено)
 а) перейдите в Администрирование
 б) откройте  Консоль заданий, "Сервис->Консоль заданий"
 в) настройке два заданий: укажите использовать, укажите пользователя администраторов в поле и настройке расписание выполнения

![image](https://user-images.githubusercontent.com/24763549/52478032-1dc47500-2bb5-11e9-8ba0-7f39e92082e3.png)
  г) после настройки у вас должны запуститься задания.

защита от запуска многократного одинаковых заданий стоит, но видимо не предусматривала запуск без активных заданий.

4) Далее для корректной работы задний (запуска сценариев) для службы под которой выполняется работа базы "Тестирование 3.0" должна быть активна настройка взаимодействия с рабочим столом. Иначе не корректно будет выполняться запуск и работа сценариев для платформы 1С.

![image](https://user-images.githubusercontent.com/24763549/52478235-c83c9800-2bb5-11e9-965b-449cd896a1c2.png)

5) Далее должны быть настроены пути для запуска тестов.
  а) перейдите в подсистему администрирования
  б) откройте "настройки работы пользователя на рабочем месте"
  в) для пользователя администратор укажите обязательно следующие пути (на сервере):
     Путь к исполняемому файлу 1С, Путь к каталогу GIT, Путь к каталогу библиотека сценариев, Путь к каталогу отчетов выполнения тестов (туда куда будут складываться тесты,  Путь к внешнему сервису для автоматизации 'Win Automation UI'.

6) Если вы хотите, чтобы в тестах сохранялись картинки, то обязательно нужно создать задание запуска WinAutomationUI и включить его запуск в задание проверки (самое начало).
Конструктор задания для этой задачи еще не готов, но его можно сделать руками, если требуется могу описать как.

**Comment by ivanov660** [comment]
7. У вас должны быть настроены как минимум две базы:
Текущая база - это параметры подключения к базе "Тестирование 3.0", это требуется для запуска сценариев и загрузки отчетов
Тестируемый клиент (к примеру, ТК ЕРП) - это другая база(ы), в которой выполняются проверки.
В задании проверка вам надо выбирать тестируемый клиент (к примеру, ТК ЕРП).
В видео уроке про эту особенность рассказыается

**Comment by SolovevaIV** [comment]
Спасибо, 
настройки для пользователей были настроены как на видео уроке, оказалось были проблемы с настройками регламентного задания и настройками создания заданий.

Если не составит труда, то было бы интересно узнать как сделать конструктор задания для WinAutomationUI

Помимо этого, из-за того что долго пыталась разобраться насоздавала много элементов, которые в дальнейшем не нужны, есть ли возможность их удалить после того, как я пометила их на удаление? Не смогла найти обработчик для удаления элементов.

**Comment by ivanov660** [comment]
1. **Про удаление**:

а). Если вы про удаление справочников, то через "все функции"->стандартные->удаление помеченных объектов.
б). Для регистров по заданиям, то откройте форму регистра нажмите Ctrl+A и далее Del.

2. **Временное решение запуска в задании WinAutomationUI** (как только будет конструктор создан, необходимо будет перейти на него ).

**а) Создайте новое действие "Запустить ExternalAutomationUI"** с типом "выполнить произвольный код":

`// I) если открыт, то закроем
Сообщение = "";
PID = ПланировщикЗаданийСервер.ПолучитьЗначениеПользовательскойПеременной(Неопределено,"ExternAutomationUI 8080");

Если НЕ PID=Неопределено Тогда
	ПланировщикЗаданийКлиентСервер.ЗавершитьПроцессЛокально(PID,Сообщение);
КонецЕсли;

// II) запустить и сохранить в параметр
Сообщение = "";
PID = ПланировщикЗаданийКлиентСервер.ЗапуститьПриложениеЛокально("\\общая папка или локальный путь\erp-tests\ExternAutomationUI\WinAutomationUI.exe -StartWebServer -Port 8080",Сообщение);
Если PID>0 Тогда
	ПланировщикЗаданийСервер.УстановитьЗначениеПользовательскойПеременной(Неопределено,"ExternAutomationUI 8080",PID);
КонецЕсли;
`
![image](https://user-images.githubusercontent.com/24763549/52555940-28bd1680-2dfc-11e9-8485-264ac438ae0e.png)

**б) Создайте задание "Запуск ExternalAutomationUI"** и в него "Состав заданий" добавьте действие "Запустить ExternalAutomationUI"
![image](https://user-images.githubusercontent.com/24763549/52558486-9882cf80-2e03-11e9-9578-52ecc6773dce.png)

**г) Создайте еще одно действие "Закрыть ExternalAutomationUI"**

`// закрыть и удалить параметр
Сообщение = "";
PID = ПланировщикЗаданийСервер.ПолучитьЗначениеПользовательскойПеременной(Неопределено,"ExternAutomationUI 8080");

Если НЕ PID=Неопределено Тогда
	ПланировщикЗаданийКлиентСервер.ЗавершитьПроцессЛокально(PID,Сообщение);
	ПланировщикЗаданийСервер.УдалитьЗначениеПользовательскойПеременной(Неопределено,"ExternAutomationUI 8080");
КонецЕсли;`
![image](https://user-images.githubusercontent.com/24763549/52558587-d7188a00-2e03-11e9-88b8-21bbd4a27dd8.png)
**д) Создайте задание "Закрыть ExternalAutomationUI"** и используете в составе данные шага г)

**е) Теперь в задании проверки** укажите с номером "0" задание "ЗАпуск ExternalAutomationUI", а самым последним шагом "Закрытие ExternalAutomationUI"
![image](https://user-images.githubusercontent.com/24763549/52558703-47bfa680-2e04-11e9-8779-ebf1b991ddb3.png)

**Comment by ivanov660** [comment]
@SolovevaIV предлагаю закрыть обсуждение. Для обсуждения других вопросов создаем отдельные задачи.
