### ISSUE TITLE
Ошибка при создании пакетного задания

### ISSUE THREAD

**Issue by SolovevaIV** [ivanov660/TestingTool-3#46]
При создании пакетного задания в конструкторе валится ошибка

Шаги по воспроизведению ошибки:
1. Откройте Задания в Планировщике
2. Нажмите Создать по шаблоны
3. Выберете Выполнение проверки (набора заданий)
4. Заполнить поля и нажать Вперед
5. Ошибка

**Ожидаемое поведение**
Переход на следующий шаг создания проверки

**Screenshots**
![image](https://user-images.githubusercontent.com/46512357/56346101-6c544800-61d2-11e9-9ac6-236bf7555d43.png)

**Desktop (please complete the following information):**
 - OS: Win 8.1
 - Тестирование и разработка (3.18.10.30)

**Comment by ivanov660** [comment]
Какая версия плагина у Вас интегрирована?
С спике дополнительных отчетов и обработок отображается информация о версиях - текущий вариант должен быть 2018.01.11. 
Последняя версия конфигурации тестирования также имеет версию: 3.19.02.26

**Comment by SolovevaIV** [comment]
Проблема решилась обновлением конфигурации.
Объясните пожалуйста, как необходимо настроить переменные действий и заданий, если у меня все тесты загружаются из файла, не из каталога git
![image](https://user-images.githubusercontent.com/46512357/56485561-8305e200-64e5-11e9-8cd1-18cc183bd686.png)

Тесты запускаются, но не проходят

И еще вопрос, можно ли изменить настройки, чтобы тесты запускались в текущем сеансе (win 8.1)

**Comment by ivanov660** [comment]
**По настройкам (проверьте)**:
1. Рекомендуем все же использовать GIT (думаю стоит сделать видео-урок по работе с распределенным хранилищем для тестов, тут все очень просто). 
2. Если вы не используете GIT (по каким либо причинам), то определиться с каталогом в котором лежат тесты (варианты по приоритету). (скорее всего у вас также настроено корректно):
        а) если вы работаете на своей машине, сервер отдельно (там где стоит конфигурация тестирования), тогда необходимо создать общий каталог в котором будут хранится тесты (к примеру, **\\server\tests\**, а локальный путь на этом сервере пусть будет **с:\tests\**). Важно чтобы сервер имел доступ к этому каталогу от системной учетной записи (рекомендуем общий каталог для хранения тестов расположить на этом сервере, где установлена конфигурация тестирования)
       б) если вы работаете на сервере (там где установлена конфигурация тестирования), то можно использовать локальный каталог (к примеру, **с:\tests\**). Его вы указываете в настройках пользователя.

Как бы технически для конфигурации тестирования нет понятия GIT, она оперирует каталогами. Вы можете к примеру, вручную синхронизировать папки между разработчиками и разруливать конфликты.

3. Задания тестов или проверок запускаются регламентным заданием на стороне сервера (скорее всего у вас верно настроено).
а) убедитесь, что регламентное задание запускается под Администратором (с полными правами).
![image](https://user-images.githubusercontent.com/24763549/56560826-28848880-65ae-11e9-9ed0-cab7e36ad60a.png)
б) настройка работы пользователя Администратора выглядит что-то вроде
![image](https://user-images.githubusercontent.com/24763549/56561253-71890c80-65af-11e9-8e5d-a003eadbaa85.png)

**По ошибке**:
Ошибка информирует, что задание запустилось, но не произошло подключение. Это могло произойти из-за:
а) не верных настроек подключения или запуска тестируемого клиента (предприятия); проверьте корректность командной строки на запуск.
![image](https://user-images.githubusercontent.com/24763549/56563556-a9df1980-65b4-11e9-9919-35c529e2c285.png)

`"C:\Program Files\1cv8\8.3.12.1685.local\bin\1cv8c.exe"  /S "сервер:порт/база тестирования 3.0" /N"QA-бот" ¶ /Execute "c:\tests\МенеджерСценарногоТеста.epf" /LogUI /TESTMANAGER ¶ /C"¶ TestUI c:\tests\сценарии\БП Перемещение товаров.xml ¶ TestLogUI c:\temp\Отчеты ¶ TestLibDirUI c:\tests\библиотека ¶ TestConnectionStringUI localhost/ut_11_demo¶ **TestUser1CUI** Администратор (ОрловАВ) ¶ TestPass1CUI  ¶ TestPortUI 1579¶ TestProg1C C:\Program Files\1cv8\8.3.12.1685.local\bin\1cv8c.exe ¶ TestUrlExternAutomationUI http://localhost:8091¶ TestScreenShotUI Actions¶ TestReportNameUI report-503_БП Перемещение товаров ¶ TestReportFormatUI AllureXML¶"`
обратите внимание на параметры после:
 - TestConnectionStringUI - должно быть указана строка подключения к серверу и базе тестирования (сервер:порт/имя базы)
- TestUser1CUI - имя пользователя
- TestPass1CUI - его пароль
другие параметры должны быть также заполнены
б) Другие причины. 

Проверить можно что там происходит:

- Включив режим сохранения снимков экранов в режим все - тогда вы сможете увидеть картинки экранов тестируемого приложения на каждый шаг (используем WinAutomationUI.exe).

- Либо включив на сервере доступ к 0-му сеансу (под ним запускается на сервере), откроете сеанс и посмотрите что-там происходит. Как настроить говорил тут[https://github.com/ivanov660/TestingTool-3/issues/18#issuecomment-428462712](url)

**Comment by SolovevaIV** [comment]
Происходит следующее:
1. Запускается конфигурация 1С как Менеджер тестирования
2. Снова запускается конфигурация т1С как Клиент тестирования
3. Затем ничего не происходит, так как, видимо из-за вот этой ошибки в логах при подключении к Менеджеру Сценарных Тестов:
{ВнешняяОбработка.МенеджерСценарногоТеста.Форма.Модуль_ОбработкаДействий.Форма(73)}: Не смогли установить соединение! {ВнешняяОбработка.МенеджерСценарногоТеста.Форма.Модуль_ОбработкаДействий.Форма(62)}: Ошибка при вызове метода контекста (УстановитьСоединение): Ошибка подключения к клиенту тестирования. Запустите клиента или укажите правильные параметры подключения.

4. Затем запускается еще раз конфигурация 1С, но уже для загрузки отчета, где появляется вот эта ошибка
{ВнешняяОбработка.ЗагрузкаЛогаJUnitXMLТеста.Форма.Форма.Форма(401)}: Ошибка при вызове метода контекста (ПредопределенноеЗначение)
	РезультатВыполнения = ПредопределенноеЗначение("Перечисление.ВариантыСерьезностиДефектов.ПустаяСсылка");
по причине:
Предопределенное значение "Перечисление.ВариантыСерьезностиДефектов.ПустаяСсылка" не найдено.

**Comment by ivanov660** [comment]
1. Обратите внимание, что по п. 4. Судя по всему вы запускаете в отличной базе от базы тестирование 3.0.
`Предопределенное значение "Перечисление.ВариантыСерьезностиДефектов.ПустаяСсылка" не найдено.` - говорит о том что другая конфигурация. Загрузить можно отчет, только в базу тестирования 3.0.

2. По вопросу ошибки соединения. Вы запускаете в базе со свойством "TESTMANAGER". Иначе была бы ошибка:
`....Тип не определен (ТестируемоеПриложение)`
Проверьте, что версия менеджера самая последняя версия "2019.03.29".

Что может мешать:
- стоит не верный api в настройках,
- стоит флаг "ЭтоНеПредприятие1С в настройках;
- стоят не верные настройки в свойствах шага подключения (если используется параметр или указано вручную значение) - api и ЭтоНеПредприятие1С;
- клиент не запускается в режиме клиента проверьте, что в заголовке базы есть "Клиент тестирования";
![image](https://user-images.githubusercontent.com/24763549/56594650-e2531780-65f5-11e9-858b-92c8ac34ba18.png)
- попробуйте смените порт тестирования на отличный, к примеру, 1555 или 1768;
- могут быть заблокированы порты для подключения на сервере, нужно открыть.

**Comment by uramalyutin** [comment]
> * Включив режим сохранения снимков экранов в режим все - тогда вы сможете увидеть картинки экранов тестируемого приложения на каждый шаг (используем WinAutomationUI.exe).

Немного оффтоп: подскажите, пожалуйста, есть ли где-то инструкция по настройке использования снимков экрана? Стараюсь следить за новой информацией по продукту, но, видимо, пропустил.

**Comment by ivanov660** [comment]
> > * Включив режим сохранения снимков экранов в режим все - тогда вы сможете увидеть картинки экранов тестируемого приложения на каждый шаг (используем WinAutomationUI.exe).
> 
> Немного оффтоп: подскажите, пожалуйста, есть ли где-то инструкция по настройке использования снимков экрана? Стараюсь следить за новой информацией по продукту, но, видимо, пропустил.

1. Документация в процессе подготовки. Надеюсь в ближайшее время удастся сделать небольшой прорыв в данном направлении. 
2. Чтобы включить сохранение снимков в самом менеджере в локальном (ручном) режиме требуется выполнить следующий операции:
а) запустить сервис WinAutomationUI.exe и включить режим сервера (по умолчанию порт 8080)
б) настроить в параметрах менеджера опции сохранения снимков экранов
![image](https://user-images.githubusercontent.com/24763549/57785955-525b4600-773b-11e9-9169-fb2658897ee8.png)
в) выполнить запуск тестируемых клиентов (а не подключаться к открытым) иначе менеджер не сможет точно определить.
г) Запустить тест, по завершению он сохранит отчет в формате Allure и картинки.
д) этот отчет может быть загружен в базу.
3. Можно запускать в автоматическом режиме с этими настройками через конструктор заданий. [https://github.com/ivanov660/TestingTool-3/issues/37](url) в этой задаче я довольно подробно описал как выполнить подобную настройку в планировщике.
![image](https://user-images.githubusercontent.com/24763549/57787213-a2d3a300-773d-11e9-8029-de7d5c0233e9.png)

**Comment by ivanov660** [comment]
@SolovevaIV закрываем?
