### ISSUE TITLE
Неправильно формируется отчет о тестировании

### ISSUE THREAD

**Issue by uramalyutin** [ivanov660/TestingTool-3#47]
В отчете о выполнении содержится не полная информация (нет информации о выполнении шагов теста).

![01](https://user-images.githubusercontent.com/11212311/58188877-150a3180-7cc2-11e9-88b0-db5f01e4e7ec.jpg)

При загрузке этого отчета появляется ошибка (хотя весь тест выполнился без ошибок).

![02](https://user-images.githubusercontent.com/11212311/58188912-25baa780-7cc2-11e9-81be-42588a775418.jpg)

Проверка создается, но протоколы не загружаются.

Думаю, что это произошло после обновления конфигурации последними изменениями из репозитория, т.к. я не уверен, что правильно обновил все плагины. Возможно часть плагинов осталась не обновлена и из-за этого они работают некорректно.

Помогите разобраться.

**Comment by uramalyutin** [comment]
Закрывайте. Оказалась не обновлена обработка МенеджерСценарногоТеста.epf.

**Comment by ivanov660** [comment]
Старайтесь обновлять на последние версии.

**Comment by uramalyutin** [comment]
Для создания тестов я использовал обновленную, а вот та, которая используется во время автоматического запуска проверки, осталась не обновленная (я как-то вообще забыл про нее). Но теперь я использую её же и для создания тестов, думаю, что больше не забуду.
А вообще я как-то не разобрался как пользоваться обработкой "Управление обновлением плагинов" и пока что обновил все вручную.
