### ISSUE TITLE
Ошибка при запуске юнит - теста

### ISSUE THREAD

**Issue by maximsamokhval** [ivanov660/TestingTool-3#53]
**Опишите ошибку**
При выполнении процедуры ПланировщикЗаданийСервер.ВыполнениеДействийЗаданийИзПуллаПоТипуЗапуститьПриложение ЗапуститьПриложение(СтрокаЗапуска) происходит запуск приложения 1С, но обработка xddTestRunner.epf не запускается.

**Воспроизведение**
Шаги по воспроизведению ошибки:
1. Создать новое задание
2. В составе заданий установить действие Выполнить юнит тест (xddTestRunner) формат 'JUnit'
3. В действиях установлены флаги "Использовать команду платформы "ЗапуститьПриложение"", "Использовать шаблон команды"
4. В поле "Обработанная строка команды" содержится текст
```
"C:\Program Files\1cv8\8.3.10.2561\bin\1cv8.exe"  %СтрокаСоединения%
 /Execute "F:\tools\xUnitFor1C\xddTestRunner.epf"  
 /C"
 xddRun ЗагрузчикФайла ""%ПутьКФайлуТеста%"";
 xddReport ГенераторОтчетаJUnitXML ""F:\tools\unit_tests\allure_result\report-%НомерПроверки%_%Тест%.xml""; 
 xddShutdown;
" 
```
5. После запуска действия - запускается 1С, но обработка xddTestRunner.epf не запускается.

**Ожидаемое поведение**
Ожидаемое поведение, при запуске действия запускается приложение 1С, выполняется запуск обработки xddTestRunner.epf и её команд.

Если в отладчике вычислить финальную строку запуска и запустить её в командной строке, то всё выполняется корректно.
Пример финальной строки указан ниже

` "C:\Program Files\1cv8\8.3.10.2561\bin\1cv8.exe"   /S "clo-s-dev1:1545/1C83_Centr" /N"QAbot" /P"QAbot" /RunModeOrdinaryApplication /DisableStartupMessages  /Execute "F:\tools\xUnitFor1C\xddTestRunner.epf" /C"xddRun ЗагрузчикФайла ""F:\tools\unit_tests\UnitTest_ПроверкаРаботыМодуля_ОбменДаннымиMonolitCRM.epf"";xddReport ГенераторОтчетаAllureXML ""F:\tools\unit_tests\allure_result\report-4_ПроверкаРаботыМодуля_ОбменДаннымиMonolitCRM.xml"";   xddShutdown; "`

Скрин журнала регистрации при запуске из командной строки
![image](https://user-images.githubusercontent.com/24194977/60646418-0035c780-9e44-11e9-8be5-6b6e422ffe29.png)

Скрин журнала регистрации при запуске из **ЗапуститьПриложение(СтрокаЗапуска)**
![image](https://user-images.githubusercontent.com/24194977/60646481-2491a400-9e44-11e9-8331-4112656e4bd9.png)

**Дополнительно**
В чём может быть проблема и в какую сторону смотреть? Поиск в google не дал ответов.

**Comment by ivanov660** [comment]
1. Для определения запроса, который отправляется системе на запуск можно воспользоваться обработкой "Jenkins Skin".

![image](https://user-images.githubusercontent.com/24763549/60656562-4f85f300-9e58-11e9-8270-2fc7eb4846d0.png)

2. Могу предположить, что-то с правами запуска или доступа. Попробуйте выполнить запуск этой строки команды из обработки: ЗапускShell.epf (мы добавили его в проект TestingTool-3/TestingToolPlugins/bin/). Она позволяет запускать командную строку на сервере, клиенте, с использованием типовой процедуры 1С: "ЗапуститьПриложение" и скрипта из Shell.
2.1 Попробуйте выполнить скрипт на клиенте
2.2 Попробуйте выполнить скрипт на сервере. (И если службы сервера нет доступа к каталогу, в котором хранится файл, то ничего не запустится).
2.3 Попробуйте выполнить с фалжком "Использовать команду платформы запустить приложение"

3. Еще попробуйте в общих настройках установить "Удалять переносы строк из команды запуска"
![image](https://user-images.githubusercontent.com/24763549/60657548-367e4180-9e5a-11e9-8704-72776db81e84.png)

**Comment by ivanov660** [comment]
@maximsamokhval удалось побороть проблему?

**Comment by maximsamokhval** [comment]
@ivanov660 да, спасибо большое.
С помощью обработки ЗапускShell.epf посмотрел примеры вызовов, которые отрабатывали и нашел разницу в вызываемом методе ПланировщикЗаданийСервер.ВыполнениеДействийЗаданийИзПуллаПоТипуЗапуститьПриложение, у Вас указан третий необязательный параметр - ДожидатьсяЗавершения в процедуре ЗапуститьПриложение(СтрокаЗапуска), который и так по умолчанию Ложь. Добавил в этой процедуре этот параметр и всё заработало. В целом, нетипичное поведение платформы, если честно. 
По остальным параметрам всё было выставлено так же, как на скриноштах ("Удалять переносы строк").
Спасибо за помощь.
