### ISSUE TITLE
Ошибка загрузки лога формата Allure XML

### ISSUE THREAD

**Issue by maximsamokhval** [ivanov660/TestingTool-3#63]
**Ошибка загрузки  лога**
После выгрузки результата тестирования в лог формата Allure XML, обработка "Загрузка лога формата Allure XML" выдает ошибку 

> Поле объекта не обнаружено (title)
> 	стр_тест.ЗаголовокТеста = ПакетОбъект.title;

**Выполнить юнит тест**
Шаги по воспроизведению ошибки:
1. Выполнить команду по выполнению теста 
`"C:\Program Files\1cv8\8.3.10.2561\bin\1cv8.exe"   /S "server/database" /N"QA_BOT" /P"password" /RunModeOrdinaryApplication /DisableStartupMessages  /Execute "F:\tools\xUnitFor1C\xddTestRunner.epf"    /C"  xddRun ЗагрузчикФайла ""F:\tools\xUnitFor1C\Tests\STV_GRP\юнит_ПроверкаИнициализацииПараметровХранимыхПроцедур.epf"";  xddReport ГенераторОтчетаAllureXML ""F:\tools\unit_tests\allure_result\report-_utests_ Хранимые процедуры SQL-testsuite.xml"";   xddShutdown; "`
2. Открыть обработку "ЗагрузкаЛогаAllureXMLТеста.epf"
Выбрать файл "ee5544aa-92eb-48e7-abdd-dd662946b625-report-_utests_ хранимые процедуры sql-testsuite-testsuite.xml"

n. Ошибка должна проявиться

Обработка, генерирующая файл лога взята по адресу 
[https://github.com/silverbulleters/add/releases](url)

**Файл лога во вложении**

[log.zip](https://github.com/ivanov660/TestingTool-3/files/3590351/log.zip)

Как я понимаю, то не правильно формируется лог файл. Откуда необходимо взять обработки?

**Comment by ivanov660** [comment]
@maximsamokhval Обработка от коллег по цеху, не формирует тег "title". Мы это поле вместе с полем name используем для поиска теста в базе тестирование (т.е. находим тест или по имени или по заголовку).  Его наличие вроде не критично, поэтому в обработке загрузки поставим условие не обязательности его наличия.
Проверим данную особенность и обновим обработку загрузки отчета в формате Allure.
Сообщим, когда выйдет обновление.

**Comment by ivanov660** [comment]
@maximsamokhval попробуйте скачать обновленный вариант обработки (уже в основной ветке) "ЗагрузкаЛогаAllureXMLТеста.epf" версия "2019.09.10".
Файл отчета должен загрузиться без ошибок полученных выше.

**Comment by maximsamokhval** [comment]
@ivanov660 все отработало, спасибо.
