### ISSUE TITLE
МСТ неправильно формирует сценарный тест

### ISSUE THREAD

**Issue by uramalyutin** [ivanov660/TestingTool-3#72]
**Опишите ошибку**
При наличии в библиотечном тесте Готового блока шагов в создаваемом сценарном тесте этот готовый блок шагов становится самым первым еще до подключения к тестируемому приложению.

**Воспроизведение**
Имею библиотечный тест, в котором где-то в середине есть вызов готового блока шагов
![image](https://user-images.githubusercontent.com/11212311/72964813-e6ea6d80-3dcb-11ea-9c3f-dc7043cc8cbc.png)

Создаю сценарный тест.
![image](https://user-images.githubusercontent.com/11212311/72964878-100afe00-3dcc-11ea-8651-cdfdc0a901f1.png)
![image](https://user-images.githubusercontent.com/11212311/72964913-24e79180-3dcc-11ea-981c-0b9fd32a593d.png)
![image](https://user-images.githubusercontent.com/11212311/72964938-3892f800-3dcc-11ea-80a6-520025e5f48e.png)
![image](https://user-images.githubusercontent.com/11212311/72965003-53656c80-3dcc-11ea-8d05-da35a1e40ba6.png)

Все выглядит правильно
![image](https://user-images.githubusercontent.com/11212311/72965028-60825b80-3dcc-11ea-8002-7b3780bad4ec.png)

Теперь переключаюсь на любой другой сценарный тест и возвращаюсь к этому и готовый блок шагов копируется наверх.
![image](https://user-images.githubusercontent.com/11212311/72965092-87409200-3dcc-11ea-8e13-4d343b2c9c68.png)
![image](https://user-images.githubusercontent.com/11212311/72965138-9a536200-3dcc-11ea-951c-8cbdda2ae7cb.png)

Если в библиотечном тесте несколько готовых блоков шагов, все они копируются наверх.
Расположение готового блока шагов на ошибку не влияет. Даже если готовый блок шагов стоит сразу после подключения к тестируемому клиенту, он все равно копируется в самое начало.

**Comment by ivanov660** [comment]
Проверим. Отпишусь.

**Comment by ivanov660** [comment]
Удалось смоделировать проблему. Смотрим в чем причина.

**Comment by ivanov660** [comment]
1. Ошибка обнаружилась в процедуре сохранения сценария, а не открытия. Думаем как поправить.
2. **Исправление**. Текущий сохраненный сценарии необходимо открыть в блокноте. Найти лишний узел блока готового шага и удалить его целиком. 
В вашем случае:
-  открыть сценарий: "Больничный расчет" и поискать узел <Шаг...  котором будет тип Действие="ГотовыйБлокШагов" и наименование "Готовый блок шагов "проверка наличия строк в списке""
 - удалить данные от начала тега <Шаг до тега </Шаг>включительно.
 - после этого сценарий будет загружаться коррктно.
3. Если создавать готовые блоки шагов с типом комментарий в корне, тогда алгоритм сохранения отрабатывает корректно.
4. Об исправлении сообщим отдельно.

**Comment by uramalyutin** [comment]
Спасибо. Оберну пока все готовые блоки шагов в комментарии.

**Comment by ivanov660** [comment]
@uramalyutin 
1. внесли исправления ошибки сохранения, пока в ветке
https://github.com/ivanov660/TestingTool-3/tree/%2372_%D0%BD%D0%B5_%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D1%8C%D0%BD%D0%BE_%D1%84%D0%BE%D1%80%D0%BC%D0%B8%D1%80%D1%83%D0%B5%D1%82%D1%81%D1%8F_%D1%81%D1%86%D0%B5%D0%BD%D0%B0%D1%80%D0%B8%D0%B9_%D0%BF%D1%80%D0%B8_%D0%BE%D0%B4%D0%B8%D0%BD%D0%B0%D0%BA%D0%BE%D0%B2%D1%8B%D1%85_%D0%B3%D1%80%D1%83%D0%BF%D0%BF%D0%BE%D0%B2%D1%8B%D1%85_%D1%88%D0%B0%D0%B3%D0%B0%D1%85
2. сохраненные сценарии с подобной ошибкой придется поправить вручную.

**Comment by uramalyutin** [comment]
1. У меня ошибка воспроизвелась. Алгоритм воспроизведения точно такой же. Обработку взял из ветки #72.
2. Я уже их исправил: все готовые блоки шагов, которые стоят в иерархии на верхнем уровне, обернул в комментарий.

**Comment by uramalyutin** [comment]
Прошу прощения. Не переоткрыл обработку после замены ее в каталоге.
**Ошибка больше не воспроизводится.**

**Comment by ivanov660** [comment]
тогда закрываем ветку
